version: "3.3"
services:
  conserver:
    build: .
    command: bash -c "python ./init.py"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - MONGODB_URL
      - DEEPGRAM_KEY
      - AWS_KEY_ID
      - AWS_SECRET_KEY
      - AWS_BUCKET
      - REDIS_URL
      - LOG_LIMIT
      - HOSTNAME
    networks:
      - back-tier

  redis:
    image: "redis/redis-stack:latest"
    ports:
      - "8001:8001"
    environment:
      REDIS_ARGS: --save 20 1
    networks:
      - back-tier
    volumes:
       - ./.data:/data


networks:
  back-tier:
