version: "3.3"
services:
  conserver:
    build: .
    image: 696551158657.dkr.ecr.us-east-1.amazonaws.com/conserver
    command: bash -c "python ./init.py"
    #volumes:
    #  - .:/app
    ports:
      - "80:80"
    depends_on:
      - redis
    networks:
      - back-tier
    env_file:
      - .env

  redis:
    image: "redis/redis-stack:latest"
    #ports:
    #  - "8001:8001"
    environment:
      REDIS_ARGS: --save 20 1
    networks:
      - back-tier
    #volumes:
    #   - ./.data:/data

networks:
  back-tier:
