# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python test

on:
  push:
    #branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }} branch ${{ github.ref }} os ${{ runner.os }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        pwd
        ls -l vcon/docker_dev
        # Pull out comments and python3 specific packages as the platform already has that
        sudo apt-get install -y $(grep -vE "^\s*#" vcon/docker_dev/apt_package_list.txt | grep -v python3 | tr "\n" " ")
        python -m pip install --upgrade pip
        #python -m pip install flake8 pytest
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -r vcon/docker_dev/pip_package_list.txt
        pip install -r vcon/docker_dev/pip_server_requirements.txt
        pip freeze | grep stable
        pip freeze | grep whisper
        python3 -c "import stable_whisper;print(stable_whisper.__version__)"
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # TODO: need to get to the point where we can run this without exit-zero
        flake8 . --count --exit-zero --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest -v -rP tests
